extends RefCounted

## "Draw state" Delta; the result of a diff between
## current and last frame. Generated by GoditeBeamDiff
class_name GoditeBeamDelta

# Proximity (close) sectors (will become MeshInstance3Ds)
var prox_arrivals: Array[GoditeComposeProxSector] = []
var prox_departures: Array[GoditeComposeProxSector] = []

# Beam (far) sectors (will become MultiMeshInstance3Ds)
var beam_arrivals: Array[GoditeComposeBeamSector] = []
var beam_departures: Array[GoditeComposeBeamSector] = []

# Most distant sectors (will become MeshInstance3Ds IF baked mesh available)
var dist_arrivals: Array[GoditeCompositeCell] = []
var dist_departures: Array[GoditeCompositeCell] = []

# Editor only; cells for visualisation of the colorful blocks
var cell_arrivals: Array[GoditeCompositeCell] = []
var cell_departures: Array[GoditeCompositeCell] = []

var count: int
var time_us: int  

func is_beam_empty() -> bool:
	return beam_arrivals.is_empty() and beam_departures.is_empty()

func is_prox_empty() -> bool:
	return prox_arrivals.is_empty() and prox_departures.is_empty()

func is_empty() -> bool:
	return is_beam_empty() and is_prox_empty()
